version: '3.4'

services:
  proyectocolprofesionales:
    build: .  # Esto construirá la imagen desde tu Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DBColProfessional;User Id=sa;Password=Passw0rd;
    ports:
      - "8080:80"
    depends_on:
      - sqlserver  # Esto asegura que el servicio de SQL Server se inicie antes

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./migration/migration.sql:/migration/migration.sql
      - ./migration/db.sql:/migration/db.sql
      - sql_data:/var/opt/mssql
    entrypoint: ["/bin/bash", "/entrypoint.sh"]  # Ejecuta el script de inicio para crear la DB

volumes:
  sql_data:
