services:
  proyectocolprofesionales:
    image: kevineduardoalanesortega/proyectocolprofesionales:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=DBColProfessional;User Id=sa;Password=Passw0rd;
      - SmtpSettings__Server=smtp.gmail.com..0
      - SmtpSettings__Port=587
      - SmtpSettings__Username=kevin.tpa17@gmail.com
      - SmtpSettings__Password=ktkwbunjorytvipc
      - SmtpSettings__Sender=kevin.tpa17@gmail.com
    ports:
      - "8080:80"
 
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
   
    environment:
   
      SA_PASSWORD: "Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
 
    volumes:
        #esta linea de codigo es para ejecutar el .sql a el docker y se creara la base de datos
      - ./migration/migration.sql:/migration/migration.sql
        #es para ejecutar la segunda linea de cracion en el docker la base de datos
      - ./migration/db.sql:/migration/db.sql
     
      - ./entrypoint.sh:/entrypoint.sh
      - sql_data:/var/opt/mssql
    entrypoint: ["/bin/bash", "/entrypoint.sh"]
 
volumes:
  sql_data: