// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoColProfesionales.Data;

#nullable disable

namespace ProyectoColProfesionales.Migrations
{
    [DbContext(typeof(DataDbContext))]
    partial class DataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProyectoColProfesionales.Models.Activity1", b =>
                {
                    b.Property<int>("idActivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idActivity"), 1L, 1);

                    b.Property<string>("auditorium")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateActivity")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("hasAssistance")
                        .HasColumnType("bit");

                    b.Property<bool>("hasPayment")
                        .HasColumnType("bit");

                    b.Property<int>("idThesis")
                        .HasColumnType("int");

                    b.Property<int>("idUserLastUpdate")
                        .HasColumnType("int");

                    b.Property<int>("idUserRegister")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("latitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("longitude")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("stateActivity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint");

                    b.HasKey("idActivity");

                    b.ToTable("Activity1");
                });

            modelBuilder.Entity("ProyectoColProfesionales.Models.ActivityProfessional", b =>
                {
                    b.Property<int>("idActivityProfessional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idActivityProfessional"), 1L, 1);

                    b.Property<int>("idActivity")
                        .HasColumnType("int");

                    b.Property<int>("idProfessional")
                        .HasColumnType("int");

                    b.HasKey("idActivityProfessional");

                    b.ToTable("ActivityProfessional");
                });

            modelBuilder.Entity("ProyectoColProfesionales.Models.ActivityVoucher", b =>
                {
                    b.Property<int>("idActivityVoucher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idActivityVoucher"), 1L, 1);

                    b.Property<int>("idActivity")
                        .HasColumnType("int");

                    b.Property<string>("nameFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("voucherFile")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("voucherType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idActivityVoucher");

                    b.ToTable("ActivityVoucher");
                });

            modelBuilder.Entity("ProyectoColProfesionales.Models.Person", b =>
                {
                    b.Property<int>("IdPerson")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPerson"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdUserLastUpdate")
                        .HasColumnType("int");

                    b.Property<int>("IdUserRegister")
                        .HasColumnType("int");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("IdPerson");

                    b.ToTable("People");
                });

            modelBuilder.Entity("ProyectoColProfesionales.Models.Professional", b =>
                {
                    b.Property<int>("idProfessional")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idProfessional"), 1L, 1);

                    b.Property<string>("carrera")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idPerson")
                        .HasColumnType("int");

                    b.Property<int>("idUserLastUpdate")
                        .HasColumnType("int");

                    b.Property<int>("idUserRegister")
                        .HasColumnType("int");

                    b.Property<DateTime>("lastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("status")
                        .HasColumnType("tinyint");

                    b.Property<string>("universidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idProfessional");

                    b.ToTable("Professional");
                });
#pragma warning restore 612, 618
        }
    }
}
